// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IPLookupResult struct {
	UUID         string `json:"uuid"`
	IPAddress    string `json:"ip_address"`
	ResponseCode string `json:"response_code"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}
